# Generated by Django 4.2.3 on 2023-07-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lms_users',
            name='status',
            field=models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Librarian'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
